openapi: 3.1.0

info:
  title: CARELOGIX DGII Worker API
  version: "5.0"
  description: >
    API oficial utilizada por el sistema CARELOGIX para subir facturas en formato
    de imagen a OneDrive mediante Microsoft Graph y para insertar líneas 606/607
    en el archivo Excel contable.  
    Autor: Master Sensei – CARELOGIX CRG SRL.
  contact:
    name: Master Sensei
    email: soporte@carelogix.pro

servers:
  - url: https://factura-laamigra-workers-dev.jit.dev

paths:

  /uploadFacturaImagen:
    post:
      operationId: uploadFacturaImagen
      summary: Sube una factura en imagen a OneDrive.
      description: >
        Paso 1 del flujo DGII.  
        Requiere fileName, fileBase64 y fechaComprobante (AAAAMMDD).  
        La imagen se guarda en la carpeta mensual YYYYMM generada automáticamente.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - fileName
                - fileBase64
                - fechaComprobante
              properties:
                fileName:
                  type: string
                  description: Nombre final del archivo (PNG/JPG).
                fileBase64:
                  type: string
                  description: Cadena Base64 completa de la imagen.
                fechaComprobante:
                  type: string
                  description: Fecha del comprobante AAAAMMDD utilizada para crear la carpeta.
      responses:
        "200":
          description: Imagen subida exitosamente.
        "400":
          description: Parámetros inválidos.
        "500":
          description: Error interno del Worker.

  /insertFactura:
    post:
      operationId: insertFactura
      summary: Inserta una línea contable (606/607) en Excel.
      description: >
        Paso 2 del flujo DGII.  
        Recibe la matriz 'values', donde cada fila incluye todas las columnas del
        606 o 607, incluyendo la imagenUrl en la última columna.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - values
              properties:
                values:
                  type: array
                  description: Matriz de una o varias filas para Excel (Table1).
                  items:
                    type: array
      responses:
        "200":
          description: Línea insertada correctamente.
        "400":
          description: Error en los datos enviados.
        "500":
          description: Error interno al insertar datos.

  /debug:
    post:
      operationId: debug
      summary: Devuelve el JSON recibido sin validación.
      description: Endpoint auxiliar para pruebas.
      responses:
        "200":
          description: El Worker devolvió el cuerpo recibido.
